name: release-management
on:
  workflow_dispatch:
  release:
    types: [created]
  
env:
  BUILD_ENVIRONMENT_URL: ${{vars.DEV_ENVIRONMENT_URL}}
  UAT_ENVIRONMENT_URL: ${{vars.UAT_ENVIRONMENT_URL}}
  BUILD_CLIENT_ID: ${{vars.DEV_CLIENT_ID}}
  UAT_CLIENT_ID: ${{vars.UAT_CLIENT_ID}}
  TENANT_ID: ${{vars.DEV_TENANT_ID}}

permissions:
  contents: write

jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: LinksCore
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}
    
      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: LinksFlows
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}

      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: deploy-links-flows
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: [ deploy-uat]
    steps:
      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: LinksCore
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}
    
      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: LinksFlows
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}

      - uses: ./.github/workflows/reusable-release-solution-to-uat.yml
        with:
          solution_name: deploy-links-flows
          solution_shipping_folder: out/ship/
          solution_outbound_folder: out/solutions/
          solution_source_folder: solutions/
          solution_release_folder: out/release
          secret: ${{ github.TOKEN }}